"""OpenEnv codegen / scaffold target."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from envassure.ir.models import WorldDefinition
from envassure.runtime.adapters.openenv_service import PINNED_OPENENV_VERSION

OPENENV_YAML = """\
name: {name}
openenv_pin: "{pin}"
actor_id: {actor_id}
world: world.json
server: server/environment.py
status: experimental
notes: |
  EnvAssure OpenEnv export is best-effort against openenv=={pin}.
  Unsupported semantics fail closed before startup.
"""

SERVER_PY = '''\
"""Generated OpenEnv environment server (EnvAssure scaffold)."""

from __future__ import annotations

import json
from pathlib import Path

from envassure.ir.io import load_world
from envassure.runtime import EventSourcedEnvironment
from envassure.runtime.adapters.openenv_service import (
    EnvAssureOpenEnvAction,
    OpenEnvAssureService,
)

ROOT = Path(__file__).resolve().parents[1]
WORLD = load_world(ROOT / "world.json")
_BASE = EventSourcedEnvironment(WORLD, default_actor_id="{actor_id}")
SERVICE = OpenEnvAssureService(_BASE, actor_id="{actor_id}")


def reset(seed: int | None = None, options: dict | None = None) -> dict:
    return SERVICE.reset(seed=seed, options=options).model_dump(mode="json")


def step(action: dict) -> dict:
    return SERVICE.step(EnvAssureOpenEnvAction.model_validate(action)).model_dump(mode="json")


def state() -> dict:
    return SERVICE.state().model_dump(mode="json")


if __name__ == "__main__":
    print(json.dumps({{"ok": True, "environment_id": WORLD.environment_id}}))
'''

DOCKERFILE = """\
FROM python:3.12-slim
WORKDIR /app
# Install a released envassure wheel in real images; editable for local scaffolds.
COPY . /app
RUN pip install --no-cache-dir "openenv=={pin}" "gymnasium>=0.29" \\
    && pip install --no-cache-dir -e /app 2>/dev/null || true
ENV PYTHONUNBUFFERED=1
CMD ["python", "server/environment.py"]
"""

README = """\
# {name} (OpenEnv export)

Scaffold generated by `eac export openenv`.

- Pinned upstream: `openenv=={pin}`
- Actor: `{actor_id}`
- Status: experimental / best-effort

```bash
eac test openenv --dir .
eac serve openenv --dir .
```
"""


def export_openenv_scaffold(
    world: WorldDefinition,
    output_dir: Path | str,
    *,
    actor_id: str,
    name: str | None = None,
) -> Path:
    """Write OpenEnv scaffold files for *world* under *output_dir*."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "server").mkdir(parents=True, exist_ok=True)
    env_name = name or world.environment_id.replace(".", "_")
    actors = world.index_actors()
    if actor_id not in actors:
        raise ValueError(f"unknown actor_id {actor_id!r}")

    (out / "world.json").write_text(
        json.dumps(world.model_dump(mode="json"), indent=2) + "\n",
        encoding="utf-8",
    )
    (out / "openenv.yaml").write_text(
        OPENENV_YAML.format(
            name=env_name,
            pin=PINNED_OPENENV_VERSION,
            actor_id=actor_id,
        ),
        encoding="utf-8",
    )
    (out / "server" / "environment.py").write_text(
        SERVER_PY.format(actor_id=actor_id),
        encoding="utf-8",
    )
    (out / "Dockerfile").write_text(
        DOCKERFILE.format(pin=PINNED_OPENENV_VERSION),
        encoding="utf-8",
    )
    (out / "README.md").write_text(
        README.format(name=env_name, pin=PINNED_OPENENV_VERSION, actor_id=actor_id),
        encoding="utf-8",
    )
    manifest: dict[str, Any] = {
        "schema_version": "1",
        "kind": "openenv_export",
        "environment_id": world.environment_id,
        "openenv_pin": PINNED_OPENENV_VERSION,
        "actor_id": actor_id,
        "status": "experimental",
        "image": "ghcr.io/fraware/envassure-openenv:<version>",
    }
    (out / "release-manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )
    return out
